// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5247.TestDrive.subsystems;
import org.usfirst.frc5247.TestDrive.OI;
import edu.wpi.first.wpilibj.command.Command;
//import jdk.internal.jshell.tool.resources.l10n;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
//import edu.wpi.first.wpilibj.buttons.
/**
 *
 */
public class Pnumatics extends Command {
//	public static Solenoid driveShifter;
//	public static DoubleSolenoid solenoidOne;
//	public static DoubleSolenoid solenoidCenter;
//	public static DoubleSolenoid  clawer;
	//public final JoystickButton solenoidOneT= new JoystickButton(OI.opStick, 7);
	//public final JoystickButton solenoidOneF = new JoystickButton(OI.opstick, 8);
	public Pnumatics() {
	/* 	if(solenoidOne == null) {
		solenoidOne = new DoubleSolenoid(1, 2);
		solenoidCenter = new DoubleSolenoid(3,4);
		clawer = new DoubleSolenoid(5,6);
		} */
	}
	
	//if(Robot.m_oi.xbox.getXButtonPressed()) Robot.m_subsystem.shifter.set(Value.kForward);
    //if(Robot.m_oi.xbox.getBButtonPressed()) Robot.m_subsystem.shifter.set(Value.kReverse);
	public void initialize() {
		//solenoidOn0eT.whenPressed(solenoidOne.kForward);
		
	//	if()
	}
	public void periodic() {
		
	}

	protected boolean isFinished() {
		return true;
	}
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public void toggleSolenoid() {
	/* 
			if(solenoidOne.get() == Value.kReverse) {solenoidOne.set(Value.kForward);
			}else solenoidOne.set(Value.kReverse); */
	
	}
}
